name: Playwright Tests

env:
  BUN_VERSION: 1.0.14

on:
  push:
  pull_request:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install dependencies
        run: bun install

      # necessary for ffmpeg to record videos on failure
      - name: Install Playwright Browsers Dependencies
        run: bun run playwright install ffmpeg

      - name: Run Playwright tests
        run: BUILD=1 bun run test:e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
