name: Playwright Tests

on:
  push:
  pull_request:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.tool-versions'

      - name: Install dependencies
        run: bun install

      # necessary for ffmpeg to record videos on failure
      - name: Install Playwright Browsers Dependencies
        run: bun run playwright install ffmpeg

      - name: Run Playwright tests
        run: bun run test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
