name: validate

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary

      - name: Install dependencies
        run: bun install

      - name: Check build
        run: bun run check-build

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.5.9

      - name: Install dependencies
        run: bun install

      - name: Check formatting
        run: bun run check-format

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.5.9

      - name: Install dependencies
        run: bun install

      - name: Check lint
        run: bun run check-lint

  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 0.5.9

      - name: Install dependencies
        run: bun install

      - name: Check types
        run: bun run check-types

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary

      - name: Install dependencies
        run: bun install

      - name: Check tests
        run: bun run check-tests
